debug: false

spring:
    main:
        banner-mode: off
    datasource:
        url: jdbc:tc:postgresql:18.1:///demo_for_pg_index_health_starter
        driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver

logging:
    level:
        root: info
        io.github.mfvanek.pg.core.utils.QueryExecutors: trace
