[versions]
pitest-junit5Plugin = "1.2.1"
pitest-core = "1.15.3"

[libraries]
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
postgresql = "org.postgresql:postgresql:42.7.1"
logback-classic = "ch.qos.logback:logback-classic:1.2.12"
slf4j-api = "org.slf4j:slf4j-api:2.0.10" # to be compatible with Spring Boot 2.7.X
apache-commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.11.0"
awaitility = "org.awaitility:awaitility:4.2.0"
apache-commons-lang3 = "org.apache.commons:commons-lang3:3.14.0"
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.15.5"
pitest-dashboard-reporter = "it.mulders.stryker:pit-dashboard-reporter:0.2.1"
