[libraries]
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
postgresql = "org.postgresql:postgresql:42.7.3"
logback-classic = "ch.qos.logback:logback-classic:1.2.12"
slf4j-api = "org.slf4j:slf4j-api:2.0.13" # to be compatible with Spring Boot 2.7.X
apache-commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.12.0"
awaitility = "org.awaitility:awaitility:4.2.1"
apache-commons-lang3 = "org.apache.commons:commons-lang3:3.14.0"
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.16.1"
