[versions]
spring-boot = "2.7.18"
detekt = "1.23.8"
commons-lang3 = "3.17.0"
assertj = "3.27.3"
testcontainers = "1.21.0"
junit = "5.12.2"
mockito = "5.17.0"
forbiddenapis = "3.9"

[libraries]
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
postgresql = "org.postgresql:postgresql:42.7.5"
slf4j-simple = "org.slf4j:slf4j-simple:1.7.36" # to be compatible with Spring Boot 2.7.X
apache-commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.13.0"
awaitility = "org.awaitility:awaitility:4.3.0"
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.19.4"
spring-boot-starter-root = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-autoconfigure-processor = { group = "org.springframework.boot", name = "spring-boot-autoconfigure-processor", version.ref = "spring-boot" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter-data-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-jdbc", version.ref = "spring-boot" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version.ref = "detekt" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
forbiddenapis = { group = "de.thetaphi", name = "forbiddenapis", version.ref = "forbiddenapis" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }

[plugins]
spring-boot-gradlePlugin = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
