[versions]
spring-boot = "2.7.18"
detekt = "1.23.7"
commons-lang3 = "3.17.0"
slf4j = "1.7.36" # to be compatible with Spring Boot 2.7.X
assertj = "3.25.3"
testcontainers = "1.20.1"
junit = "5.10.2"
mockito = "5.12.0"
forbiddenapis = "3.7"

[libraries]
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
postgresql = "org.postgresql:postgresql:42.7.4"
logback-classic = "ch.qos.logback:logback-classic:1.2.12"
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
apache-commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.12.0"
awaitility = "org.awaitility:awaitility:4.2.2"
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.16.2"
spring-boot-starter-root = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-autoconfigure-processor = { group = "org.springframework.boot", name = "spring-boot-autoconfigure-processor", version.ref = "spring-boot" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter-data-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-jdbc", version.ref = "spring-boot" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version.ref = "detekt" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
forbiddenapis = { group = "de.thetaphi", name = "forbiddenapis", version.ref = "forbiddenapis" }

[plugins]
spring-boot-gradlePlugin = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
