[versions]
spring-boot-v3 = "3.4.13"
spring-boot-v4 = "4.0.1"
slf4j = "2.0.17" # to be compatible with Spring Boot 3.4.X
detekt = "1.23.8"
commons-lang3 = "3.20.0"
assertj = "3.27.6"
testcontainers = "2.0.3" # we do not align the testcontainers version with Spring Boot BOM
mockito = "5.21.0"
forbiddenapis = "3.10"
junit = "6.0.1"

[libraries]
jspecify = "org.jspecify:jspecify:1.0.0"
postgresql = "org.postgresql:postgresql:42.7.8"
jackson-bom = "com.fasterxml.jackson:jackson-bom:2.18.5" # to be compatible with Spring Boot 3.4.X
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
slf4j-jul = { group = "org.slf4j", name = "jul-to-slf4j", version.ref = "slf4j" }
apache-commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.14.0"
awaitility = "org.awaitility:awaitility:4.3.0"
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:4.3"
spring-boot-v3-starter-root = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot-v3" }
spring-boot-v3-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot-v3" }
spring-boot-v3-autoconfigure-processor = { group = "org.springframework.boot", name = "spring-boot-autoconfigure-processor", version.ref = "spring-boot-v3" }
spring-boot-v3-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot-v3" }
spring-boot-v3-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc", version.ref = "spring-boot-v3" }
spring-boot-v3-starter-json = { group = "org.springframework.boot", name = "spring-boot-starter-json", version.ref = "spring-boot-v3" }
spring-boot-v4-starter-jdbc-main = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc", version.ref = "spring-boot-v4" }
spring-boot-v4-starter-jdbc-test = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc-test", version.ref = "spring-boot-v4" }
spring-boot-v4-starter-jackson2 = { group = "org.springframework.boot", name = "spring-boot-jackson2", version.ref = "spring-boot-v4" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version.ref = "detekt" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
forbiddenapis = { group = "de.thetaphi", name = "forbiddenapis", version.ref = "forbiddenapis" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
liquibase-core = "org.liquibase:liquibase-core:5.0.1"
liquibase-sessionlock = "com.github.blagerweij:liquibase-sessionlock:1.6.9"
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
arch-unit = "com.tngtech.archunit:archunit-junit5:1.4.1"

[plugins]
spring-boot-v3-gradle-plugin = { id = "org.springframework.boot", version.ref = "spring-boot-v3" }
spring-boot-v4-gradle-plugin = { id = "org.springframework.boot", version.ref = "spring-boot-v4" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
lombok = { id = "io.freefair.lombok", version = "9.1.0" }
