debug: false

spring:
    main:
        banner-mode: off
    liquibase:
        change-log: classpath:/changelog/changelog.yaml
        default-schema: custom_ds_schema

pgih:
    custom:
        datasource:
            jdbc-url: jdbc:tc:postgresql:18.1:///demo_for_pg_index_health_starter?TC_INITSCRIPT=init.sql
            driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
            maximum-pool-size: 5
