debug: false

spring:
    datasource:
        # see resources/init.sql
        username: custom_user
        password: customUserPassword
    main:
        banner-mode: log
    liquibase:
        change-log: classpath:/changelog/changelog.yaml
